#!/bin/bash

curl -X POST \
-H "X-Parse-Application-Id: iT8NyJO0dChjLyfVsHUTM8UZQLSBBJLxd43AX9IY" \
-H "Content-Type: image/jpeg" --data-binary '@myPicture.jpg' \
http://localhost:1337/parse/files/pic.jpg
